### ISSUE TITLE
gtk_window_set_screen: assertion 'GDK_IS_SCREEN (screen)' failed

### ISSUE THREAD

**Issue by myf** [aidanholm/luakit#155]
when i tried to do `luakit URL` to send a new window to an existing luakit session, then console responds `connection refused` and creates a blank page

**Comment by aidanholm** [comment]
Which commit are you building from? When did the assertion occur? Did the `luakit URL` instance (as opposed to the pre-existing instance) of luakit crash? If so, any backtrace? I'm assuming you've built luakit with libunique support? (`USE_UNIQUE = 1`, the default)

IIRC "connection refused" indicates that WebKit cannot find `luakit.so`. Have you built luakit with (the default) `DEVELOPMENT_PATHS = 1`? If so, is there a `luakit.so` in the current directory (luakit uses current directory if that setting is enabled)?

This is odd, because although the webkit extension search path is set before `config/rc.lua` loads, if you're using libunique the temporary instance will just send IPC messages to the main instance; it shouldn't open any views itself and it shouldn't change the working directory of the main instance.

**Comment by aidanholm** [comment]
Opening a new luakit instance was clobbering the existing instance's IPC socket. fix pushed at 70d1efa
