### ISSUE TITLE
Remove support for gtk2 and webkit1

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#28]
Is there any need for keeping support for those old versions around? AFAIR you said webkit1 currently is broken in some modules. Gnome published their new approach towards LTS releases which states gtk-3.26 will be stable in ~1 year, don't know how that will affect gtk2. Also webkit1 will be unsupported at some point.

As this is an issue many luakit-users would be interested in I think discussing this in the official bugtracker at https://github.com/luakit/luakit I would ask you @aidanholm if I may suggest to give you write access so that your great work on gtk3/webkit2 could be upstreamed and discussed.

**Comment by aidanholm** [comment]
I am planning to remove support for both GTK 2 and WebKit 1, since supporting them clutters the source code, and most of what I have implemented is only useful/necessary for WebKit 2. I have some coursework to complete over the next few days but will start removing WebKit 1 support soon. One reason I've been keeping support so far is to find areas where features are not yet implemented (e.g. WebKit 2 cookie support).

**Comment by aidanholm** [comment]
Some WIP in `remove-webkit1` branch, seems to work fine so far.

**Comment by ff2000** [comment]
remove-webkit1 compiled fine and a short test did not show any runtime issue.

**Comment by aidanholm** [comment]
Thanks for trying it out. Next I'll need to figure out a minimum GTK 3 version, and remove support for GTK2, etc.

**Comment by aidanholm** [comment]
Support for WebKit 1 and GTK 2 removed.
