### ISSUE TITLE
Xvfb always starts on :0 in tests

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#317]
no matter if :0 is free or taken
```
Starting Xvfb
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
```

**Comment by Ygrex** [comment]
even though I was able to run Xvfb, run_tests get stuck after that, priv.spawn just waits until the subprocess finishes

how should tests be run?

**Comment by aidanholm** [comment]
Thanks for the PR! Tests should be run through `make run_tests` or by directly running `lua tests/run_test.lua`.

Do you mean that the `priv.spawn({"Xvfb", xvfb_display, "-screen", "0", "800x600x8"})` line blocks?

**Comment by Ygrex** [comment]
yes exactly, spawn() gets stuck on posix.read(r, 1024) in a parent

**Comment by aidanholm** [comment]
It's possible that the child is never spawned; i.e. that `posix.execp` fails. This is because if the child process is spawned successfully, the pipe between parent and child will close and `read()` will return. Are there any errors logged?

I think the correct solution is to replace this code with a small C Lua library that would wrap the GLib process spawning APIs. This takes advantage of a very well-tested implementation, and (with some other changes to `run_tests.lua`) will remove `luaposix` and `bit` as dependencies.

**Comment by Ygrex** [comment]
thank you, I was not sure it is a bug because there is no docs explaining how to run the tests
reported it separately in https://github.com/aidanholm/luakit/issues/320

**Comment by aidanholm** [comment]
Ok, thanks; I'll close this then. I've also opened #321 for the missing tests documentation.
