### ISSUE TITLE
Customize bookmark entry display order

### ISSUE THREAD

**Issue by halocaridina** [aidanholm/luakit#352]
How might one arrange the order of the bookmark page or is that only possible by manipulating the sqlite DB itself?

Thanks in advance and appreciate your maintenance of this browser.

**Comment by aidanholm** [comment]
It'd be nice to expose that through the module, a la `bookmarks_chrome.order = "title desc"`. But in the meantime you can manually edit `lib/bookmarks_chrome.lua`; search for and modify `ORDER BY created DESC`.

You're welcome; glad you like it!

**Comment by halocaridina** [comment]
Hi aidanholm,

Thank you for the quick reply and info, I'll have a look at making that modification.

What I was looking for is an option to reorder the bookmark list as new ones are added (as new bookmarks are added they appear at the top of the list; could they be moved from that position to another?).

Cheers, Halocaridina

**Comment by aidanholm** [comment]
Hey Halocaridina;

`bookmarks_chrome` rebuilds the entire HTML for the bookmarks list after every edit. They appear at the top of the list because the SQL search query orders results by creation date descending. If you'd like them to appear somewhere other than at the top, currently you need to change the SQL query as described above.

If you'd like some ordering that can't be expressed in SQL for some reason, you could always change it to a `SELECT ALL`, and then filter to the current page and sort in Lua.

Hope this helps!

**Comment by halocaridina** [comment]
Great, this information should help in what I want to do.

Cheers!!
