### ISSUE TITLE
Switching on WebKit strings fails with locales other than English

### ISSUE THREAD

**Issue by zappathustra** [aidanholm/luakit#404]
When the page you are visiting is still loading (as indicated in the statusbar), and you try to load a new one (e.g. by clicking on a link that is already visible) or simply reloading the current one, it generally fails with:

>Unable to load page
A problem occurred while loading the URL https://wiki.archlinux.org/index.php/Luakit
La demande de chargement a été annulée
Proxy in use: system default
Try again [BUTTON]

The third line means something like "The request for download has been cancelled"; I wanted the proper translation, so I started Luakit with `LC_ALL=C luakit` and then the problem vanished! It exists only when LC_ALL is empty (any value will do).

I'm running on Arch, and luakit -V returns

>luakit 2012.09.13-r1-1713-g2de65f50

(built this morning from luakit-git in AUR).

**Comment by zappathustra** [comment]
I've been a little too fast. The problem comes from the "fr_FR.UTF-8" locale, and setting LC_ALL to that will not make the problem disappear (as expected, since it is my default locale). Also, only LANG and LC_MESSAGES are relevant: changing one or the other to anything but "fr_FR.UTF-8" solves the problem, which is what LC_ALL does by overriding all locale values.

**Comment by aidanholm** [comment]
Ugh. WebKit issues a load-failed event when you cancel the load (since all load operations either finish completely or fail) with the error message "Load request cancelled". Luakit hooks onto this event and shows a pretty error page. In `lib/error_page.lua`, we specifically check for that string "Load request cancelled" and ignore the error if that happens, but of course that's not going to work if your locale is french! :)

There's a few possible solution paths here, but for now the best workaround is to run it with `LANG=C`.

**Comment by aidanholm** [comment]
This should be fixed now, at 3a839ba7; sorry it took so long! Error pages should now mostly be in your native language, except for certificate error messages, which are generated differently.
