### ISSUE TITLE
insert mode fails on inspector

### ISSUE THREAD

**Issue by hippi777** [aidanholm/luakit#411]
hi!

i've tried to write width:.... into the inspector, and then luakit recognized the w as a hotkey...

btw it's still not the latest version, but i'm following the progress, and i didn't see anything related

**Comment by aidanholm** [comment]
Hi!

That's https://github.com/luakit/luakit/issues/74: it's a pretty old issue, and tough to solve. The workaround I use is to use passthrough mode (`ctrl-z`) when using the inspector. It's not perfect, though, because (`ctrl-z`) is also "undo" for the inspector.

BTW this issue tracker is my old one, pre-unfork; it's best to submit issues here instead: https://github.com/luakit/luakit/issues/

**Comment by hippi777** [comment]
thx :) and sorry for getting lost, i've just typed in the nav bar 'aid' :D

**Comment by aidanholm** [comment]
No worries :)
